#!/usr/bin/env python

env = SConscript("../third_party/godot-cpp/SConstruct")
env.Append(CPPPATH=["include"])

sources = Glob("src/*.cpp")

target_path = "../../addons/rcs_core/bin/"
target_name = "rcs_core{}{}".format(env["suffix"], env["SHLIBSUFFIX"])

library = env.SharedLibrary(target=target_path + target_name, source=sources)
Default(library)
